
ALTER TABLE public.landing_pages
  ADD COLUMN hero_title TEXT,
  ADD COLUMN hero_subtitle TEXT,
  ADD COLUMN hero_cta_text TEXT DEFAULT 'Comprar Agora',
  ADD COLUMN hero_cta_link TEXT,
  ADD COLUMN hero_image TEXT,
  ADD COLUMN product_image TEXT,
  ADD COLUMN background_image TEXT,
  ADD COLUMN logo_image TEXT,
  ADD COLUMN logo_size TEXT DEFAULT 'medium',
  ADD COLUMN price_original NUMERIC,
  ADD COLUMN price_current NUMERIC,
  ADD COLUMN price_installments TEXT,
  ADD COLUMN about_title TEXT,
  ADD COLUMN about_description TEXT,
  ADD COLUMN cta_title TEXT,
  ADD COLUMN cta_subtitle TEXT,
  ADD COLUMN color_primary TEXT DEFAULT '#8B5CF6',
  ADD COLUMN color_accent TEXT DEFAULT '#10B981',
  ADD COLUMN color_background TEXT DEFAULT '#0a0a0f',
  ADD COLUMN color_text TEXT DEFAULT '#ffffff',
  ADD COLUMN color_text_highlight TEXT DEFAULT '#a855f7',
  ADD COLUMN color_icons TEXT DEFAULT '#8B5CF6',
  ADD COLUMN font_heading TEXT DEFAULT 'Inter',
  ADD COLUMN font_body TEXT DEFAULT 'Inter',
  ADD COLUMN video_enabled BOOLEAN DEFAULT false,
  ADD COLUMN video_title TEXT,
  ADD COLUMN video_url TEXT,
  ADD COLUMN video_thumbnail TEXT,
  ADD COLUMN video_hide_controls BOOLEAN DEFAULT true,
  ADD COLUMN donation_enabled BOOLEAN DEFAULT true,
  ADD COLUMN donation_title TEXT,
  ADD COLUMN donation_description TEXT,
  ADD COLUMN donation_pix_key TEXT,
  ADD COLUMN donation_pix_name TEXT,
  ADD COLUMN donation_qr_code TEXT,
  ADD COLUMN access_key TEXT,
  ADD COLUMN whatsapp_message TEXT,
  ADD COLUMN features JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN how_it_works JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN testimonials JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN faqs JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN secure_purchase_items JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN pricing_tiers JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN social_proof_enabled BOOLEAN DEFAULT true,
  ADD COLUMN social_proof_product_name TEXT DEFAULT 'o Gerador',
  ADD COLUMN social_proof_customers JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN social_proof_credits JSONB DEFAULT '[200,500,1000,2000]'::jsonb,
  ADD COLUMN meta_title TEXT,
  ADD COLUMN meta_description TEXT,
  ADD COLUMN og_image TEXT,
  ADD COLUMN facebook_pixel TEXT,
  ADD COLUMN google_analytics TEXT,
  ADD COLUMN google_tag_manager TEXT,
  ADD COLUMN tiktok_pixel TEXT,
  ADD COLUMN section_order JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN pix_enabled BOOLEAN DEFAULT true,
  ADD COLUMN pix_key TEXT,
  ADD COLUMN pix_name TEXT,
  ADD COLUMN pix_qr_base TEXT,
  ADD COLUMN hero_title_highlight TEXT,
  ADD COLUMN hero_badge_text TEXT DEFAULT 'Oferta Limitada',
  ADD COLUMN hero_daily_renewal_text TEXT,
  ADD COLUMN hero_extra_prices JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN hero_extra_renewals JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN promo_text TEXT,
  ADD COLUMN promo_link TEXT,
  ADD COLUMN custom_package_options JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN why_choose_items JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN checkout_product_subtitle TEXT,
  ADD COLUMN checkout_product_description TEXT,
  ADD COLUMN checkout_badge_text TEXT DEFAULT 'OFERTA LIMITADA',
  ADD COLUMN checkout_benefits JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN checkout_enabled BOOLEAN DEFAULT true,
  ADD COLUMN nav_buttons JSONB DEFAULT '[]'::jsonb;
